### ISSUE TITLE
PHP/Java Bridge output buffering with PHP7. 4 & Tomcat 9

### ISSUE THREAD

**Issue by SagnikGanguly96** [micw/php-java-bridge#2]
Hi I'm Sagnik Ganguly, I've installed PHP/Java Bridge in Tomcat 9 on Windows with PHP 7.4. But the problem is that I can't set the output buffering or it's not working as the php.ini property output_buffering is set to 4096 and it's working on Apache HTTPD but in Tomcat the response is displayed only after the entire body is loaded instead of displaying the loaded content. May I know how can I fix it?

**Comment by micw** [comment]
Hello,

I don't maintain the project, I just forked it from sf.net 10 years ago. Sorry, cannot help with that.
